### ISSUE TITLE
2015/10/05~2015/10/11

### ISSUE THREAD

**Issue by smartac-front-end** [smartac-frontend/doc#1]

**Comment by iamjoel** [comment]
- [关于CSS的专业建议](https://github.com/AllThingsSmitty/css-protips)
- [为什么我们需要`repeating-linear-gradient` ](https://css-tricks.com/why-do-we-have-repeating-linear-gradient-anyway/)

**Comment by 759325100** [comment]
*  浏览器内部工作原理 (http://kb.cnblogs.com/page/129756/)

**Comment by 759325100** [comment]
- [浏览器内部工作原理](http://kb.cnblogs.com/page/129756/)

**Comment by iamjoel** [comment]
- [用CSS来找出两张图的差异](http://www.jianshu.com/p/00af744f52d1)

**Comment by huchuanping** [comment]
- [前端组件库](http://top.css88.com/archives/660)

**Comment by iamjoel** [comment]
@huchuanping 那评论要在当前时间段。放在 https://github.com/smartac-frontend/doc/issues/5
