### ISSUE TITLE
前端常用网站整理

### ISSUE THREAD

**Issue by iamjoel** [smartac-frontend/doc#20]
包括
- 前端博客, 如[div.io](http://div.io/) 这样的
- 开发者的博客网站
- 资源类网站
- 工具类网站：如 caniuse

**Comment by jslygljy** [comment]
前端外刊  技术文章  http://zhuanlan.zhihu.com/FrontendMagazine

**Comment by guoqing2015** [comment]
前端乱炖 http://www.html-js.com/

**Comment by freedomdebug** [comment]
国内UED大全


腾讯 
腾讯CDC http://cdc.tencent.com/ CDC(Customer Research & User Experience Design Center)腾讯用户研究与体验设计中心
腾讯ISD http://isd.tencent.com/
腾讯UED http://ued.qq.com/
腾讯WSD http://wsd.tencent.com/
腾讯TGideas http://tgideas.qq.com/ 腾讯游戏的专业设计团队
腾讯ISUX http://isux.tencent.com/ ISUX (Internet Service User Experience)腾讯互联网用户体验设计部
腾讯GDC http://gdc.qq.com/ GDC（Game Design Center）QQ游戏设计中心
腾讯ECD http://ecd.tencent.com/

百度 
百度UEO http://www.baiduux.com/ UEO（User Experience Organization) 百度泛用户体验平台
百度MUX http://mux.baidu.com/ MUX(Mobile User Experience) 百度无线用户体验部。
百度UED http://ued.baidu.com/ 百度商业产品用户体验部
百度XDC http://xdc.baidu.com/ 百度用户体验部

阿里 
淘宝UED http://ued.taobao.com/
阿里巴巴(中文站 )UEDhttp://www.aliued.cn/
阿里巴巴(国际站)UED http://www.aliued.com/
阿里妈妈UED http://ued.alimama.com/
口碑网UED http://ued.koubei.com/
支付宝UED http://ued.alipay.com/
支付宝PED http://ped.alipay.com/PED(Product Experience Design)支付宝产品体验设计部
天猫UED http://ued.tmall.com/
天猫SED http://sed.tmall.com/
一淘网UX http://ux.etao.com/


新浪 
新浪UED http://ued.sina.com/
微博UDC http://udc.weibo.com/
新浪ChinaUED http://blog.sina.com.cn/chinaued
新浪SNS梦之队 http://blog.sina.com.cn/cnsns
新浪UED http://blog.sina.com.cn/uimedia
新浪乐居UED http://ued.leju.com

网易 
网易UEDC http://uedc.163.com/ UEDC（User Experience Design Center）网易用户体验设计中心
网易GUX http://gux.163.com/ GUX（Game User eXperience）网易游戏用户体验中心
网易杭州UED  http://ucd.blog.163.com/

搜狐 
搜狐UED http://ued.sohu.com/
搜狗UED  http://ued.sogou.com/
搜狐焦点UED http://ued.focus.cn/
搜狐MUED http://mued.sohu.com/ Mobile User Experience Design 搜狐移动门户中心 用户体验团队


其他 
盛大UED http://www.sndaued.com/
携程UED http://ued.ctrip.com/
360奇舞团 http://www.75team.com/
人人FED http://fed.renren.com/ FED（Front End Develop and Design）
爱词霸UED http://ued.iciba.com/
金蝶友商网UED http://www.kdued.com/
5173UED http://ued.5173.com/
19楼UED http://blog.19ued.com/
财付通TID http://tid.tenpay.com/ TID（Tenpay Innovation Design）财付通设计中心。
迅雷CUED http://cued.xunlei.com/ 迅雷用户体验设计中心
驴妈妈UED http://ued.lvmama.com/
3G门户UED http://ued.3g.cn/
虎扑用户体验设计工厂 http://ued.hupu.com/
第九城市UED http://www.the9ued.com/
MyEChinese UED http://ued.myechinese.com/
彩程UED http://blog.mycolorway.com/
昆仑游戏UED http://www.gameued.com/
搜道网UED http://d2.sodao.com/
360UXC http://uxc.360.cn/

**Comment by iamjoel** [comment]
前端博客聚合资源
- [前端乱炖](http://www.html-js.com/)
- [稀土掘金](http://gold.xitu.io/#/tag/%E5%89%8D%E7%AB%AF)
- [div.io](http://div.io/)
- [开发者头条](http://toutiao.io/)
- [前端De早读课](http://www.zaoduke.net/)

**Comment by iamjoel** [comment]
整理的内容移动至 https://github.com/smartac-frontend/doc/blob/master/bookmark.md

**Comment by freedomdebug** [comment]
gulp-book：傻瓜式gulp入门https://github.com/nimojs/gulp-book
ruby+sass+compass雪碧图：http://www.cnblogs.com/xljzlw/p/4771103.html
